[dependencies]
jellyfin = {path = "../../jellyfin-rs"}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-form-widget = {path = "../form"}
jellyhaj-keybinds-widget = {path = "../keybinds"}
jellyhaj-widgets-core = {path = "../core"}
tokio = {features = ["time"], workspace = true}
color-eyre.workspace = true
futures-util.workspace = true
ratatui.workspace = true
serde.workspace = true
valuable.workspace = true
parking_lot.workspace = true
serde_json.workspace = true

[package]
name = "jellyhaj-login-widget"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
