[dependencies]
jellyfin = {path = "../jellyfin-rs"}
jellyhaj-async-task = {path = "../async-task"}
spawn = {path = "../spawn"}
tokio = {features = ["macros", "sync"], workspace = true}
color-eyre.workspace = true
futures-intrusive.workspace = true
parking_lot.workspace = true
tracing.workspace = true
sqlx.workspace = true
serde_json.workspace = true

[package]
name = "jellyhaj-event-listener"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
