[dependencies]
jellyfin = {path = "../../jellyfin-rs"}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-image = {path = "../image"}
jellyhaj-widgets-core = {path = "../core"}
tokio = { features = ["sync"], workspace = true }
color-eyre.workspace = true
ratatui.workspace = true
tracing.workspace = true
valuable.workspace = true
serde_json.workspace = true
spawn = { path = "../../spawn" }
sqlx.workspace = true
jellyhaj-event-listener = { path = "../../event-listener" }
crossterm = { workspace = true, features = ["osc52"] }

[package]
name = "jellyhaj-entry-widget"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
