[dependencies]
color-eyre.workspace = true
crossterm = { workspace = true, features = ["osc52"] }
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-widgets-core = {path = "../core"}
serde_json.workspace = true
tokio = {features = ["sync"], workspace = true}
tracing.workspace = true
tui-tree-widget.workspace = true
valuable.workspace = true

[package]
name = "jellyhaj-inspect-widget"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
