[dependencies]
jellyfin = {path = "../../jellyfin-rs"}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-form-widget = {path = "../form"}
jellyhaj-keybinds-widget = {path = "../keybinds"}
jellyhaj-widgets-core = {path = "../core"}
color-eyre.workspace = true
valuable.workspace = true

[package]
name = "jellyhaj-refresh-item-widget"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
