[package]
name = "jellyhaj-helper-view"
rust-version.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
jellyhaj-core = { version = "0.1.0", path = "../../jellyhaj-core" }
jellyhaj-helper-widget = { version = "0.1.0", path = "../../widgets/helper" }
jellyhaj-widgets-core = { version = "0.1.0", path = "../../widgets/core" }

[lints]
workspace = true
