[dependencies]
jellyhaj-item-list = {path = "../item-list"}
jellyhaj-widgets-core = {path = "../core"}
color-eyre.workspace = true
ratatui.workspace = true
tracing.workspace = true

[package]
name = "jellyhaj-item-screen"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
