[dependencies]
proc-macro2 = {workspace = true}
quote = {workspace = true}
syn = {features = [
  "clone-impls",
  "derive",
  "extra-traits",
  "full",
  "parsing",
  "printing"
], workspace = true}
convert_case.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
prettydiff.workspace = true
prettyplease.workspace = true

[package]
name = "jellyhaj-form-derive-impl"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
