[package]
name = "jellyhaj-http-client-view"

[package.version ]
workspace = true

[package.edition ]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
jellyfin = { path = "../../jellyfin-rs" }
jellyhaj-context = { path = "../../context" }
jellyhaj-core = { path = "../../jellyhaj-core" }
jellyhaj-fetch-view = { path = "../fetch" }
jellyhaj-form-widget = { path = "../../widgets/form" }
jellyhaj-keybinds-widget = { path = "../../widgets/keybinds" }
jellyhaj-widgets-core = { path = "../../widgets/core" }
valuable.workspace = true

[lints]
workspace = true
