[dependencies]
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-keybinds-widget = {path = "../../widgets/keybinds"}
jellyhaj-log-widget = {path = "../../widgets/log"}
jellyhaj-widgets-core = {path = "../../widgets/core"}
color-eyre.workspace = true
spawn = { path = "../../spawn" }

[package]
name = "jellyhaj-log-view"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
