[dependencies]
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-inspect-widget = {path = "../../widgets/inspect"}
jellyhaj-keybinds-widget = {path = "../../widgets/keybinds"}
jellyhaj-widgets-core = {path = "../../widgets/core"}
color-eyre.workspace = true
serde_json.workspace = true
spawn = { path = "../../spawn" }

[package]
name = "jellyhaj-inspect-view"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
