[dependencies]
jellyfin = {path = "../../jellyfin-rs"}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-fetch-widget = {path = "../../widgets/fetch"}
jellyhaj-keybinds-widget = {path = "../../widgets/keybinds"}
jellyhaj-loading-widget = {path = "../../widgets/loading"}
jellyhaj-widgets-core = {path = "../../widgets/core"}
keybinds = {path = "../../keybinds"}
spawn = {path = "../../spawn"}
color-eyre.workspace = true
futures-util.workspace = true
ratatui.workspace = true
tokio.workspace = true
tracing.workspace = true

[package]
name = "jellyhaj-fetch-view"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
