/* automatically generated by rust-bindgen 0.72.1 */

#[doc = " For initializing the mpv OpenGL state via `MPV_RENDER_PARAM_OPENGL_INIT_PARAMS`."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_opengl_init_params {
    #[doc = " This retrieves OpenGL function pointers, and will use them in subsequent\n operation.\n Usually, you can simply call the GL context APIs from this callback (e.g.\n glXGetProcAddressARB or wglGetProcAddress), but some APIs do not always\n return pointers for all standard functions (even if present); in this\n case you have to compensate by looking up these functions yourself when\n libmpv wants to resolve them through this callback.\n libmpv will not normally attempt to resolve GL functions on its own, nor\n does it link to GL libraries directly."]
    pub get_proc_address: ::std::option::Option<
        unsafe extern "C" fn(
            ctx: *mut ::std::os::raw::c_void,
            name: *const ::std::os::raw::c_char,
        ) -> *mut ::std::os::raw::c_void,
    >,
    #[doc = " Value passed as ctx parameter to `get_proc_address()`."]
    pub get_proc_address_ctx: *mut ::std::os::raw::c_void,
}
#[doc = " For `MPV_RENDER_PARAM_OPENGL_FBO`."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_opengl_fbo {
    #[doc = " Framebuffer object name. This must be either a valid FBO generated by\n `glGenFramebuffers()` that is complete and color-renderable, or 0. If the\n value is 0, this refers to the OpenGL default framebuffer."]
    pub fbo: ::std::os::raw::c_int,
    #[doc = " Valid dimensions. This must refer to the size of the framebuffer. This\n must always be set."]
    pub w: ::std::os::raw::c_int,
    #[doc = " Valid dimensions. This must refer to the size of the framebuffer. This\n must always be set."]
    pub h: ::std::os::raw::c_int,
    #[doc = " Underlying texture internal format (e.g. `GL_RGBA8`), or 0 if unknown. If\n this is the default framebuffer, this can be an equivalent."]
    pub internal_format: ::std::os::raw::c_int,
}
#[doc = " Deprecated. For `MPV_RENDER_PARAM_DRM_DISPLAY`."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_opengl_drm_params {
    pub fd: ::std::os::raw::c_int,
    pub crtc_id: ::std::os::raw::c_int,
    pub connector_id: ::std::os::raw::c_int,
    pub atomic_request_ptr: *mut *mut _drmModeAtomicReq,
    pub render_fd: ::std::os::raw::c_int,
}
#[doc = " For `MPV_RENDER_PARAM_DRM_DRAW_SURFACE_SIZE`."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_opengl_drm_draw_surface_size {
    #[doc = " size of the draw plane surface in pixels."]
    pub width: ::std::os::raw::c_int,
    #[doc = " size of the draw plane surface in pixels."]
    pub height: ::std::os::raw::c_int,
}
#[doc = " For `MPV_RENDER_PARAM_DRM_DISPLAY_V2`."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_opengl_drm_params_v2 {
    #[doc = " DRM fd (int). Set to -1 if invalid."]
    pub fd: ::std::os::raw::c_int,
    #[doc = " Currently used crtc id"]
    pub crtc_id: ::std::os::raw::c_int,
    #[doc = " Currently used connector id"]
    pub connector_id: ::std::os::raw::c_int,
    #[doc = " Pointer to a drmModeAtomicReq pointer that is being used for the renderloop.\n This pointer should hold a pointer to the atomic request pointer\n The atomic request pointer is usually changed at every renderloop."]
    pub atomic_request_ptr: *mut *mut _drmModeAtomicReq,
    #[doc = " DRM render node. Used for VAAPI interop.\n Set to -1 if invalid."]
    pub render_fd: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _drmModeAtomicReq {
    pub _address: u8,
}
