/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_render_context {
    _unused: [u8; 0],
}
#[doc = " Not a valid value, but also used to terminate a params array. Its value\n is always guaranteed to be 0 (even if the ABI changes in the future)."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_INVALID: mpv_render_param_type = 0;
#[doc = " The render API to use. Valid for `mpv_render_context_create()`.\n\n Type: char*\n\n Defined APIs:\n\n   `MPV_RENDER_API_TYPE_OPENGL`:\n      OpenGL desktop 2.1 or later (preferably core profile compatible to\n      OpenGL 3.2), or `OpenGLES` 2.0 or later.\n      Providing `MPV_RENDER_PARAM_OPENGL_INIT_PARAMS` is required.\n      It is expected that an OpenGL context is valid and \"current\" when\n      calling `mpv_render`_* functions (unless specified otherwise). It\n      must be the same context for the same `mpv_render_context`."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_API_TYPE: mpv_render_param_type = 1;
#[doc = " Required parameters for initializing the OpenGL renderer. Valid for\n `mpv_render_context_create()`.\n Type: `mpv_opengl_init_params`*"]
pub const mpv_render_param_type_MPV_RENDER_PARAM_OPENGL_INIT_PARAMS: mpv_render_param_type = 2;
#[doc = " Describes a GL render target. Valid for `mpv_render_context_render()`.\n Type: `mpv_opengl_fbo`*"]
pub const mpv_render_param_type_MPV_RENDER_PARAM_OPENGL_FBO: mpv_render_param_type = 3;
#[doc = " Control flipped rendering. Valid for `mpv_render_context_render()`.\n Type: int*\n If the value is set to 0, render normally. Otherwise, render it flipped,\n which is needed e.g. when rendering to an OpenGL default framebuffer\n (which has a flipped coordinate system)."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_FLIP_Y: mpv_render_param_type = 4;
#[doc = " Control surface depth. Valid for `mpv_render_context_render()`.\n Type: int*\n This implies the depth of the surface passed to the render function in\n bits per channel. If omitted or set to 0, the renderer will assume 8.\n Typically used to control dithering."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_DEPTH: mpv_render_param_type = 5;
#[doc = " ICC profile blob. Valid for `mpv_render_context_set_parameter()`.\n Type: `mpv_byte_array`*\n Set an ICC profile for use with the \"icc-profile-auto\" option. (If the\n option is not enabled, the ICC data will not be used.)"]
pub const mpv_render_param_type_MPV_RENDER_PARAM_ICC_PROFILE: mpv_render_param_type = 6;
#[doc = " Deprecated\n Ambient light in lux. Valid for `mpv_render_context_set_parameter()`.\n Type: int*\n This can be used for automatic gamma correction."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_AMBIENT_LIGHT: mpv_render_param_type = 7;
#[doc = " X11 Display, sometimes used for hwdec. Valid for\n `mpv_render_context_create()`. The Display must stay valid for the lifetime\n of the `mpv_render_context`.\n Type: Display*"]
pub const mpv_render_param_type_MPV_RENDER_PARAM_X11_DISPLAY: mpv_render_param_type = 8;
#[doc = " Wayland display, sometimes used for hwdec. Valid for\n `mpv_render_context_create()`. The `wl_display` must stay valid for the\n lifetime of the `mpv_render_context`.\n Type: struct `wl_display`*"]
pub const mpv_render_param_type_MPV_RENDER_PARAM_WL_DISPLAY: mpv_render_param_type = 9;
#[doc = " Better control about rendering and enabling some advanced features. Valid\n for `mpv_render_context_create()`.\n\n This conflates multiple requirements the API user promises to abide if\n this option is enabled:\n\n  - The API user's render thread, which is calling the `mpv_render`_*()\n    functions, never waits for the core. Otherwise deadlocks can happen.\n    See \"Threading\" section.\n  - The callback set with `mpv_render_context_set_update_callback()` can now\n    be called even if there is no new frame. The API user should call the\n    `mpv_render_context_update()` function, and interpret the return value\n    for whether a new frame should be rendered.\n  - Correct functionality is impossible if the update callback is not set,\n    or not set soon enough after `mpv_render_context_create()` (the core can\n    block while waiting for you to call `mpv_render_context_update()`, and\n    if the update callback is not correctly set, it will deadlock, or\n    block for too long).\n\n In general, setting this option will enable the following features (and\n possibly more):\n\n  - \"Direct rendering\", which means the player decodes directly to a\n    texture, which saves a copy per video frame (\"vd-lavc-dr\" option\n    needs to be enabled, and the rendering backend as well as the\n    underlying GPU API/driver needs to have support for it).\n  - Rendering screenshots with the GPU API if supported by the backend\n    (instead of using a suboptimal software fallback via libswscale).\n\n Warning: do not just add this without reading the \"Threading\" section\n          above, and then wondering that deadlocks happen. The\n          requirements are tricky. But also note that even if advanced\n          control is disabled, not adhering to the rules will lead to\n          playback problems. Enabling advanced controls simply makes\n          violating these rules fatal.\n\n Type: int*: 0 for disable (default), 1 for enable"]
pub const mpv_render_param_type_MPV_RENDER_PARAM_ADVANCED_CONTROL: mpv_render_param_type = 10;
#[doc = " Return information about the next frame to render. Valid for\n `mpv_render_context_get_info()`.\n\n Type: `mpv_render_frame_info`*\n\n It strictly returns information about the _next_ frame. The implication\n is that e.g. `mpv_render_context_update()`'s return value will have\n `MPV_RENDER_UPDATE_FRAME` set, and the user is supposed to call\n `mpv_render_context_render()`. If there is no next frame, then the\n return value will have `is_valid` set to 0."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_NEXT_FRAME_INFO: mpv_render_param_type = 11;
#[doc = " Enable or disable video timing. Valid for `mpv_render_context_render()`.\n\n Type: int*: 0 for disable, 1 for enable (default)\n\n When video is timed to audio, the player attempts to render video a bit\n ahead, and then do a blocking wait until the target display time is\n reached. This blocks `mpv_render_context_render()` for up to the amount\n specified with the \"video-timing-offset\" global option. You can set\n this parameter to 0 to disable this kind of waiting. If you do, it's\n recommended to use the target time value in `mpv_render_frame_info` to\n wait yourself, or to set the \"video-timing-offset\" to 0 instead.\n\n Disabling this without doing anything in addition will result in A/V sync\n being slightly off."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_BLOCK_FOR_TARGET_TIME: mpv_render_param_type = 12;
#[doc = " Use to skip rendering in `mpv_render_context_render()`.\n\n Type: int*: 0 for rendering (default), 1 for skipping\n\n If this is set, you don't need to pass a target surface to the render\n function (and if you do, it's completely ignored). This can still call\n into the lower level APIs (i.e. if you use OpenGL, the OpenGL context\n must be set).\n\n Be aware that the render API will consider this frame as having been\n rendered. All other normal rules also apply, for example about whether\n you have to call `mpv_render_context_report_swap()`. It also does timing\n in the same way."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_SKIP_RENDERING: mpv_render_param_type = 13;
#[doc = " Deprecated. Not supported. Use `MPV_RENDER_PARAM_DRM_DISPLAY_V2` instead.\n Type : struct `mpv_opengl_drm_params`*"]
pub const mpv_render_param_type_MPV_RENDER_PARAM_DRM_DISPLAY: mpv_render_param_type = 14;
#[doc = " DRM draw surface size, contains draw surface dimensions.\n Valid for `mpv_render_context_create()`.\n Type : struct `mpv_opengl_drm_draw_surface_size`*"]
pub const mpv_render_param_type_MPV_RENDER_PARAM_DRM_DRAW_SURFACE_SIZE: mpv_render_param_type = 15;
#[doc = " DRM display, contains drm display handles.\n Valid for `mpv_render_context_create()`.\n Type : struct `mpv_opengl_drm_params_v2`*"]
pub const mpv_render_param_type_MPV_RENDER_PARAM_DRM_DISPLAY_V2: mpv_render_param_type = 16;
#[doc = " `MPV_RENDER_API_TYPE_SW` only: rendering target surface size, mandatory.\n Valid for `MPV_RENDER_API_TYPE_SW` & `mpv_render_context_render()`.\n Type: int\\[2\\] (e.g.: int s\\[2\\] = {w, h}; param.data = &s\\[0\\];)\n\n The video frame is transformed as with other VOs. Typically, this means\n the video gets scaled and black bars are added if the video size or\n aspect ratio mismatches with the target size."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_SW_SIZE: mpv_render_param_type = 17;
#[doc = " `MPV_RENDER_API_TYPE_SW` only: rendering target surface pixel format,\n mandatory.\n Valid for `MPV_RENDER_API_TYPE_SW` & `mpv_render_context_render()`.\n Type: char* (e.g.: char *f = \"rgb0\"; param.data = f;)\n\n Valid values are:\n  \"rgb0\", \"bgr0\", \"0bgr\", \"0rgb\"\n      4 bytes per pixel RGB, 1 byte (8 bit) per component, component bytes\n      with increasing address from left to right (e.g. \"rgb0\" has r at\n      address 0), the \"0\" component contains uninitialized garbage (often\n      the value 0, but not necessarily; the bad naming is inherited from\n      `FFmpeg`)\n      Pixel alignment size: 4 bytes\n  \"rgb24\"\n      3 bytes per pixel RGB. This is strongly discouraged because it is\n      very slow.\n      Pixel alignment size: 1 bytes\n  other\n      The API may accept other pixel formats, using mpv internal format\n      names, as long as it's internally marked as RGB, has exactly 1\n      plane, and is supported as conversion output. It is not a good idea\n      to rely on any of these. Their semantics and handling could change."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_SW_FORMAT: mpv_render_param_type = 18;
#[doc = " `MPV_RENDER_API_TYPE_SW` only: rendering target surface bytes per line,\n mandatory.\n Valid for `MPV_RENDER_API_TYPE_SW` & `mpv_render_context_render()`.\n Type: `size_t`*\n\n This is the number of bytes between a pixel (x, y) and (x, y + 1) on the\n target surface. It must be a multiple of the pixel size, and have space\n for the surface width as specified by `MPV_RENDER_PARAM_SW_SIZE`.\n\n Both stride and pointer value should be a multiple of 64 to facilitate\n fast SIMD operation. Lower alignment might trigger slower code paths,\n and in the worst case, will copy the entire target frame. If mpv is built\n with zimg (and zimg is not disabled), the performance impact might be\n less.\n In either cases, the pointer and stride must be aligned at least to the\n pixel alignment size. Otherwise, crashes and undefined behavior is\n possible on platforms which do not support unaligned accesses (either\n through normal memory access or aligned SIMD memory access instructions)."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_SW_STRIDE: mpv_render_param_type = 19;
#[doc = " `MPV_RENDER_API_TYPE_SW` only: rendering target surface bytes per line,\n mandatory.\n Valid for `MPV_RENDER_API_TYPE_SW` & `mpv_render_context_render()`.\n Type: `size_t`*\n\n This is the number of bytes between a pixel (x, y) and (x, y + 1) on the\n target surface. It must be a multiple of the pixel size, and have space\n for the surface width as specified by `MPV_RENDER_PARAM_SW_SIZE`.\n\n Both stride and pointer value should be a multiple of 64 to facilitate\n fast SIMD operation. Lower alignment might trigger slower code paths,\n and in the worst case, will copy the entire target frame. If mpv is built\n with zimg (and zimg is not disabled), the performance impact might be\n less.\n In either cases, the pointer and stride must be aligned at least to the\n pixel alignment size. Otherwise, crashes and undefined behavior is\n possible on platforms which do not support unaligned accesses (either\n through normal memory access or aligned SIMD memory access instructions)."]
pub const mpv_render_param_type_MPV_RENDER_PARAM_SW_POINTER: mpv_render_param_type = 20;
#[doc = " Parameters for `mpv_render_param` (which is used in a few places such as\n `mpv_render_context_create()`.\n\n Also see `mpv_render_param` for conventions and how to use it."]
pub type mpv_render_param_type = ::std::os::raw::c_uint;
#[doc = " Used to pass arbitrary parameters to some `mpv_render`_* functions. The\n meaning of the data parameter is determined by the type, and each\n MPV_RENDER_PARAM_* documents what type the value must point to.\n\n Each value documents the required data type as the pointer you cast to\n void* and set on `mpv_render_param.data`. For example, if `MPV_RENDER_PARAM_FOO`\n documents the type as Something* , then the code should look like this:\n\n   Something foo = {...};\n   `mpv_render_param` param;\n   param.type = `MPV_RENDER_PARAM_FOO`;\n   param.data = & foo;\n\n Normally, the data field points to exactly 1 object. If the type is char*,\n it points to a 0-terminated string.\n\n In all cases (unless documented otherwise) the pointers need to remain\n valid during the call only. Unless otherwise documented, the API functions\n will not write to the params array or any data pointed to it.\n\n As a convention, parameter arrays are always terminated by type==0. There\n is no specific order of the parameters required. The order of the 2 fields in\n this struct is guaranteed (even after ABI changes)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_render_param {
    pub type_: mpv_render_param_type,
    pub data: *mut ::std::os::raw::c_void,
}
#[doc = " Set if there is actually a next frame. If unset, there is no next frame\n yet, and other flags and fields that require a frame to be queued will\n be unset.\n\n This is set for _any_ kind of frame, even for redraw requests.\n\n Note that when this is unset, it simply means no new frame was\n decoded/queued yet, not necessarily that the end of the video was\n reached. A new frame can be queued after some time.\n\n If the return value of `mpv_render_context_render()` had the\n `MPV_RENDER_UPDATE_FRAME` flag set, this flag will usually be set as well,\n unless the frame is rendered, or discarded by other asynchronous events."]
pub const mpv_render_frame_info_flag_MPV_RENDER_FRAME_INFO_PRESENT: mpv_render_frame_info_flag = 1;
#[doc = " If set, the frame is not an actual new video frame, but a redraw request.\n For example if the video is paused, and an option that affects video\n rendering was changed (or any other reason), an update request can be\n issued and this flag will be set.\n\n Typically, redraw frames will not be subject to video timing.\n\n Implies `MPV_RENDER_FRAME_INFO_PRESENT`."]
pub const mpv_render_frame_info_flag_MPV_RENDER_FRAME_INFO_REDRAW: mpv_render_frame_info_flag = 2;
#[doc = " If set, this is supposed to reproduce the previous frame perfectly. This\n is usually used for certain \"video-sync\" options (\"display-...\" modes).\n Typically the renderer will blit the video from a FBO. Unset otherwise.\n\n Implies `MPV_RENDER_FRAME_INFO_PRESENT`."]
pub const mpv_render_frame_info_flag_MPV_RENDER_FRAME_INFO_REPEAT: mpv_render_frame_info_flag = 4;
#[doc = " If set, the player timing code expects that the user thread blocks on\n vsync (by either delaying the render call, or by making a call to\n `mpv_render_context_report_swap()` at vsync time).\n\n Implies `MPV_RENDER_FRAME_INFO_PRESENT`."]
pub const mpv_render_frame_info_flag_MPV_RENDER_FRAME_INFO_BLOCK_VSYNC: mpv_render_frame_info_flag =
    8;
#[doc = " Flags used in `mpv_render_frame_info.flags`. Each value represents a bit in it."]
pub type mpv_render_frame_info_flag = ::std::os::raw::c_uint;
#[doc = " Information about the next video frame that will be rendered. Can be\n retrieved with `MPV_RENDER_PARAM_NEXT_FRAME_INFO`."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_render_frame_info {
    #[doc = " A bitset of `mpv_render_frame_info_flag` values (i.e. multiple flags are\n combined with bitwise or)."]
    pub flags: u64,
    #[doc = " Absolute time at which the frame is supposed to be displayed. This is in\n the same unit and base as the time returned by `mpv_get_time_us()`. For\n frames that are redrawn, or if vsync locked video timing is used (see\n \"video-sync\" option), then this can be 0. The \"video-timing-offset\"\n option determines how much \"headroom\" the render thread gets (but a high\n enough frame rate can reduce it anyway). `mpv_render_context_render()` will\n normally block until the time is elapsed, unless you pass it\n `MPV_RENDER_PARAM_BLOCK_FOR_TARGET_TIME` = 0."]
    pub target_time: i64,
}
unsafe extern "C" {
    #[doc = " Initialize the renderer state. Depending on the backend used, this will\n access the underlying GPU API and initialize its own objects.\n\n You must free the context with `mpv_render_context_free()`. Not doing so before\n the mpv core is destroyed may result in memory leaks or crashes.\n\n Currently, only at most 1 context can exists per mpv core (it represents the\n main video output).\n\n You should pass the following parameters:\n  - `MPV_RENDER_PARAM_API_TYPE` to select the underlying backend/GPU API.\n  - Backend-specific init parameter, like `MPV_RENDER_PARAM_OPENGL_INIT_PARAMS`.\n  - Setting `MPV_RENDER_PARAM_ADVANCED_CONTROL` and following its rules is\n    strongly recommended.\n  - If you want to use hwdec, possibly hwdec interop resources.\n\n @param res set to the context (on success) or NULL (on failure). The value\n            is never read and always overwritten.\n @param mpv handle used to get the core (the `mpv_render_context` won't depend\n            on this specific handle, only the core referenced by it)\n @param params an array of parameters, terminated by type==0. It's left\n               unspecified what happens with unknown parameters. At least\n               `MPV_RENDER_PARAM_API_TYPE` is required, and most backends will\n               require another backend-specific parameter.\n @return error code, including but not limited to:\n      `MPV_ERROR_UNSUPPORTED`: the OpenGL version is not supported\n                             (or required extensions are missing)\n      `MPV_ERROR_NOT_IMPLEMENTED`: an unknown API type was provided, or\n                                 support for the requested API was not\n                                 built in the used libmpv binary.\n      `MPV_ERROR_INVALID_PARAMETER`: at least one of the provided parameters was\n                                   not valid."]
    pub fn mpv_render_context_create(
        res: *mut *mut mpv_render_context,
        mpv: *mut mpv_handle,
        params: *mut mpv_render_param,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Attempt to change a single parameter. Not all backends and parameter types\n support all kinds of changes.\n\n @param ctx a valid render context\n @param param the parameter type and data that should be set\n @return error code. If a parameter could actually be changed, this returns\n         success, otherwise an error code depending on the parameter type\n         and situation."]
    pub fn mpv_render_context_set_parameter(
        ctx: *mut mpv_render_context,
        param: mpv_render_param,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Retrieve information from the render context. This is NOT a counterpart to\n `mpv_render_context_set_parameter()`, because you generally can't read\n parameters set with it, and this function is not meant for this purpose.\n Instead, this is for communicating information from the renderer back to the\n user. See `mpv_render_param_type`; entries which support this function\n explicitly mention it, and for other entries you can assume it will fail.\n\n You pass param with param.type set and param.data pointing to a variable\n of the required data type. The function will then overwrite that variable\n with the returned value (at least on success).\n\n @param ctx a valid render context\n @param param the parameter type and data that should be retrieved\n @return error code. If a parameter could actually be retrieved, this returns\n         success, otherwise an error code depending on the parameter type\n         and situation. `MPV_ERROR_NOT_IMPLEMENTED` is used for unknown\n         param.type, or if retrieving it is not supported."]
    pub fn mpv_render_context_get_info(
        ctx: *mut mpv_render_context,
        param: mpv_render_param,
    ) -> ::std::os::raw::c_int;
}
pub type mpv_render_update_fn =
    ::std::option::Option<unsafe extern "C" fn(cb_ctx: *mut ::std::os::raw::c_void)>;
unsafe extern "C" {
    #[doc = " Set the callback that notifies you when a new video frame is available, or\n if the video display configuration somehow changed and requires a redraw.\n Similar to `mpv_set_wakeup_callback()`, you must not call any mpv API from\n the callback, and all the other listed restrictions apply (such as not\n exiting the callback by throwing exceptions).\n\n This can be called from any thread, except from an update callback. In case\n of the OpenGL backend, no OpenGL state or API is accessed.\n\n Calling this will raise an update callback immediately.\n\n @param callback `callback(callback_ctx)` is called if the frame should be\n                 redrawn\n @param `callback_ctx` opaque argument to the callback"]
    pub fn mpv_render_context_set_update_callback(
        ctx: *mut mpv_render_context,
        callback: mpv_render_update_fn,
        callback_ctx: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    #[doc = " The API user is supposed to call this when the update callback was invoked\n (like all `mpv_render`_* functions, this has to happen on the render thread,\n and _not_ from the update callback itself).\n\n This is optional if `MPV_RENDER_PARAM_ADVANCED_CONTROL` was not set (default).\n Otherwise, it's a hard requirement that this is called after each update\n callback. If multiple update callback happened, and the function could not\n be called sooner, it's OK to call it once after the last callback.\n\n If an update callback happens during or after this function, the function\n must be called again at the soonest possible time.\n\n If `MPV_RENDER_PARAM_ADVANCED_CONTROL` was set, this will do additional work\n such as allocating textures for the video decoder.\n\n @return a bitset of `mpv_render_update_flag` values (i.e. multiple flags are\n         combined with bitwise or). Typically, this will tell the API user\n         what should happen next. E.g. if the `MPV_RENDER_UPDATE_FRAME` flag is\n         set, `mpv_render_context_render()` should be called. If flags unknown\n         to the API user are set, or if the return value is 0, nothing needs\n         to be done."]
    pub fn mpv_render_context_update(ctx: *mut mpv_render_context) -> u64;
}
#[doc = " A new video frame must be rendered. `mpv_render_context_render()` must be\n called."]
pub const mpv_render_update_flag_MPV_RENDER_UPDATE_FRAME: mpv_render_update_flag = 1;
#[doc = " Flags returned by `mpv_render_context_update()`. Each value represents a bit\n in the function's return value."]
pub type mpv_render_update_flag = ::std::os::raw::c_uint;
#[doc = " Flags returned by `mpv_render_context_update()`. Each value represents a bit\n in the function's return value."]
pub use self::mpv_render_update_flag as mpv_render_context_flag;
unsafe extern "C" {
    #[doc = " Render video.\n\n Typically renders the video to a target surface provided via `mpv_render_param`\n (the details depend on the backend in use). Options like \"panscan\" are\n applied to determine which part of the video should be visible and how the\n video should be scaled. You can change these options at runtime by using the\n mpv property API.\n\n The renderer will reconfigure itself every time the target surface\n configuration (such as size) is changed.\n\n This function implicitly pulls a video frame from the internal queue and\n renders it. If no new frame is available, the previous frame is redrawn.\n The update callback set with `mpv_render_context_set_update_callback()`\n notifies you when a new frame was added. The details potentially depend on\n the backends and the provided parameters.\n\n Generally, libmpv will invoke your update callback some time before the video\n frame should be shown, and then lets this function block until the supposed\n display time. This will limit your rendering to video FPS. You can prevent\n this by setting the \"video-timing-offset\" global option to 0. (This applies\n only to \"audio\" video sync mode.)\n\n You should pass the following parameters:\n  - Backend-specific target object, such as `MPV_RENDER_PARAM_OPENGL_FBO`.\n  - Possibly transformations, such as `MPV_RENDER_PARAM_FLIP_Y`.\n\n @param ctx a valid render context\n @param params an array of parameters, terminated by type==0. Which parameters\n               are required depends on the backend. It's left unspecified what\n               happens with unknown parameters.\n @return error code"]
    pub fn mpv_render_context_render(
        ctx: *mut mpv_render_context,
        params: *mut mpv_render_param,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " Tell the renderer that a frame was flipped at the given time. This is\n optional, but can help the player to achieve better timing.\n\n Note that calling this at least once informs libmpv that you will use this\n function. If you use it inconsistently, expect bad video playback.\n\n If this is called while no video is initialized, it is ignored.\n\n @param ctx a valid render context"]
    pub fn mpv_render_context_report_swap(ctx: *mut mpv_render_context);
}
unsafe extern "C" {
    #[doc = " Destroy the mpv renderer state.\n\n If video is still active (e.g. a file playing), video will be disabled\n forcefully.\n\n @param ctx a valid render context. After this function returns, this is not\n            a valid pointer anymore. NULL is also allowed and does nothing."]
    pub fn mpv_render_context_free(ctx: *mut mpv_render_context);
}
