/* automatically generated by rust-bindgen 0.72.1 */

#[doc = " Read callback used to implement a custom stream. The semantics of the\n callback match read(2) in blocking mode. Short reads are allowed (you can\n return less bytes than requested, and libmpv will retry reading the rest\n with another call). If no data can be immediately read, the callback must\n block until there is new data. A return of 0 will be interpreted as final\n EOF, although libmpv might retry the read, or seek to a different position.\n\n @param cookie opaque cookie identifying the stream,\n               returned from `mpv_stream_cb_open_fn`\n @param buf buffer to read data into\n @param size of the buffer\n @return number of bytes read into the buffer\n @return 0 on EOF\n @return -1 on error"]
pub type mpv_stream_cb_read_fn = ::std::option::Option<
    unsafe extern "C" fn(
        cookie: *mut ::std::os::raw::c_void,
        buf: *mut ::std::os::raw::c_char,
        nbytes: u64,
    ) -> i64,
>;
#[doc = " Seek callback used to implement a custom stream.\n\n Note that mpv will issue a seek to position 0 immediately after opening. This\n is used to test whether the stream is seekable (since seekability might\n depend on the URI contents, not just the protocol). Return\n `MPV_ERROR_UNSUPPORTED` if seeking is not implemented for this stream. This\n seek also serves to establish the fact that streams start at position 0.\n\n This callback can be NULL, in which it behaves as if always returning\n `MPV_ERROR_UNSUPPORTED`.\n\n @param cookie opaque cookie identifying the stream,\n               returned from `mpv_stream_cb_open_fn`\n @param offset target absolute stream position\n @return the resulting offset of the stream\n         `MPV_ERROR_UNSUPPORTED` or `MPV_ERROR_GENERIC` if the seek failed"]
pub type mpv_stream_cb_seek_fn = ::std::option::Option<
    unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void, offset: i64) -> i64,
>;
#[doc = " Size callback used to implement a custom stream.\n\n Return `MPV_ERROR_UNSUPPORTED` if no size is known.\n\n This callback can be NULL, in which it behaves as if always returning\n `MPV_ERROR_UNSUPPORTED`.\n\n @param cookie opaque cookie identifying the stream,\n               returned from `mpv_stream_cb_open_fn`\n @return the total size in bytes of the stream"]
pub type mpv_stream_cb_size_fn =
    ::std::option::Option<unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void) -> i64>;
#[doc = " Close callback used to implement a custom stream.\n\n @param cookie opaque cookie identifying the stream,\n               returned from `mpv_stream_cb_open_fn`"]
pub type mpv_stream_cb_close_fn =
    ::std::option::Option<unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void)>;
#[doc = " Cancel callback used to implement a custom stream.\n\n This callback is used to interrupt any current or future read and seek\n operations. It will be called from a separate thread than the demux\n thread, and should not block.\n\n This callback can be NULL.\n\n Available since API 1.106.\n\n @param cookie opaque cookie identifying the stream,\n               returned from `mpv_stream_cb_open_fn`"]
pub type mpv_stream_cb_cancel_fn =
    ::std::option::Option<unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void)>;
#[doc = " See `mpv_stream_cb_open_ro_fn` callback."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_stream_cb_info {
    #[doc = " Opaque user-provided value, which will be passed to the other callbacks.\n The close callback will be called to release the cookie. It is not\n interpreted by mpv. It doesn't even need to be a valid pointer.\n\n The user sets this in the `mpv_stream_cb_open_ro_fn` callback."]
    pub cookie: *mut ::std::os::raw::c_void,
    #[doc = " Callbacks set by the user in the `mpv_stream_cb_open_ro_fn` callback. Some\n of them are optional, and can be left unset.\n\n The following callbacks are mandatory: `read_fn`, `close_fn`"]
    pub read_fn: mpv_stream_cb_read_fn,
    pub seek_fn: mpv_stream_cb_seek_fn,
    pub size_fn: mpv_stream_cb_size_fn,
    pub close_fn: mpv_stream_cb_close_fn,
    pub cancel_fn: mpv_stream_cb_cancel_fn,
}
#[doc = " Open callback used to implement a custom read-only (ro) stream. The user\n must set the callback fields in the passed info struct. The cookie field\n also can be set to store state associated to the stream instance.\n\n Note that the info struct is valid only for the duration of this callback.\n You can't change the callbacks or the pointer to the cookie at a later point.\n\n Each stream instance created by the open callback can have different\n callbacks.\n\n The `close_fn` callback will terminate the stream instance. The pointers to\n your callbacks and cookie will be discarded, and the callbacks will not be\n called again.\n\n @param `user_data` opaque user data provided via `mpv_stream_cb_add()`\n @param uri name of the stream to be opened (with protocol prefix)\n @param info fields which the user should fill\n @return 0 on success, `MPV_ERROR_LOADING_FAILED` if the URI cannot be opened."]
pub type mpv_stream_cb_open_ro_fn = ::std::option::Option<
    unsafe extern "C" fn(
        user_data: *mut ::std::os::raw::c_void,
        uri: *mut ::std::os::raw::c_char,
        info: *mut mpv_stream_cb_info,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    #[doc = " Add a custom stream protocol. This will register a protocol handler under\n the given protocol prefix, and invoke the given callbacks if an URI with the\n matching protocol prefix is opened.\n\n The \"ro\" is for read-only - only read-only streams can be registered with\n this function.\n\n The callback remains registered until the mpv core is registered.\n\n If a custom stream with the same name is already registered, then the\n `MPV_ERROR_INVALID_PARAMETER` error is returned.\n\n @param protocol protocol prefix, for example \"foo\" for \"foo://\" URIs\n @param `user_data` opaque pointer passed into the `mpv_stream_cb_open_fn`\n                  callback.\n @return error code"]
    pub fn mpv_stream_cb_add_ro(
        ctx: *mut mpv_handle,
        protocol: *const ::std::os::raw::c_char,
        user_data: *mut ::std::os::raw::c_void,
        open_fn: mpv_stream_cb_open_ro_fn,
    ) -> ::std::os::raw::c_int;
}
