[package]
name = "jellyhaj-metadata-editor-view"

[package.version ]
workspace = true

[package.edition ]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
futures-util.workspace = true
jellyfin = { path = "../../jellyfin-rs" }
jellyhaj-context = { path = "../../context" }
jellyhaj-core = { path = "../../jellyhaj-core" }
jellyhaj-fetch-view = { path = "../fetch" }
jellyhaj-form-widget = { path = "../../widgets/form" }
jellyhaj-keybinds-widget = { path = "../../widgets/keybinds" }
jellyhaj-metadata-editor-widget = { path = "../../widgets/metadata-editor" }
jellyhaj-widgets-core = { path = "../../widgets/core" }

[lints]
workspace = true
