[dependencies]
crossterm = {features = ["osc52"], workspace = true}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-form-derive = {path = "../form-derive", optional = true}
jellyhaj-widgets-core = {path = "../core"}
serde = {optional = true, workspace = true}
tui-scrollview = "0.6.2"
ansi-to-tui.workspace = true
color-eyre.workspace = true
ratatui.workspace = true
valuable.workspace = true
tracing.workspace = true

[features]
serde = ["dep:serde"]
macro = ["dep:jellyhaj-form-derive"]
default = ["macro"]

[package]
name = "jellyhaj-form-widget"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
