[dependencies]
proc-macro2 = {workspace = true}
quote = {workspace = true}
syn = {features = ["clone-impls", "derive", "extra-traits", "full", "parsing", "printing"], workspace = true}

[dev-dependencies]
pretty_assertions = "1.4.1"

[package]
name = "keybinds-derive-impl"
rust-version.workspace = true
version.workspace = true
edition.workspace = true


[lints]
workspace = true
