[dependencies]
jellyfin = {path = "../../jellyfin-rs"}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-widgets-core = {path = "../core"}
player-core = {path = "../../player-core"}
color-eyre.workspace = true
futures-util.workspace = true
ratatui.workspace = true
tracing.workspace = true
valuable.workspace = true

[package]
name = "jellyhaj-player-widget"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
