[dependencies]
config = {path = "../../config"}
jellyfin = {path = "../../jellyfin-rs"}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-keybinds-widget = {path = "../../widgets/keybinds"}
jellyhaj-loading-widget = {path = "../../widgets/loading"}
jellyhaj-login-widget = {path = "../../widgets/login"}
jellyhaj-widgets-core = {path = "../../widgets/core"}
keybinds = {path = "../../keybinds"}
spawn = {path = "../../spawn"}
tokio = { features = ["macros", "process", "sync"], workspace = true }
color-eyre.workspace = true
ratatui.workspace = true
sqlx.workspace = true
toml.workspace = true
tracing.workspace = true
whoami.workspace = true
jellyhaj-form-widget = { path = "../../widgets/form" }
jellyhaj-fetch-view = { path = "../fetch" }
parking_lot.workspace = true
stats-data = { path = "../../stats-data" }

[package]
name = "jellyhaj-login-view"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
