[package]
name = "jellyhaj-context"

[package.version ]
workspace = true

[package.edition ]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
keybinds = {path = "../keybinds"}
jellyhaj-core = {path = "../jellyhaj-core"}
jellyhaj-event-listener = {path = "../event-listener"}
player-core = {path = "../player-core"}
sqlx = {workspace = true}
parking_lot = {workspace = true}
config = {path = "../config"}
image-cache = {path = "../image-cache"}
jellyfin = {path = "../jellyfin-rs"}
jellyhaj-widgets-core = {path = "../widgets/core"}
ratatui-image = {workspace = true}
ratatui = {workspace = true}
tokio = {workspace = true, features = ["sync"]}
spawn = {path = "../spawn"}
stats-data = {path = "../stats-data"}

[lints]
workspace = true
