[dependencies]
color-eyre = {workspace = true}
config = {path = "../config"}
crossbeam-epoch = "0.9.18"
jellyfin = {path = "../jellyfin-rs"}
jellyhaj-widgets-core = {path = "../widgets/core", version = "0.1.0"}
keybinds = {path = "../keybinds"}
parking_lot = {workspace = true}
ratatui = {workspace = true}
spawn = {path = "../spawn", version = "0.1.0"}
tokio = {workspace = true}
tracing = {workspace = true}
either.workspace = true
futures-intrusive.workspace = true
futures-util.workspace = true
pin-project-lite.workspace = true
valuable.workspace = true
serde.workspace = true
serde_json.workspace = true

[package]
edition = "2024"
name = "jellyhaj-core"
version = "0.1.0"


[lints]
workspace = true
