[dependencies]
jellyhaj-form-derive-impl = {path = "../form-derive-impl"}
syn.workspace = true

[lib]
proc-macro = true

[package]
name = "jellyhaj-form-derive"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true



[lints]
workspace = true
