

[start]
effect= """
fx::fade_from_fg(bg, (500, Linear))
"""
fps = 30

[exit]
effect = """
fx::parallel(&[
    fx::fade_to_fg(bg, (250, Linear)),
    fx::dissolve(250)
])
"""
fps = 30

[fetch.exit]
[fetch.start]
