
# General Info:
# This file maps key inputs to commands.
# You can even define key combinations.
# Instead of traditional keybinds where you have to press
# multiple keys simultaneously you combine them by pressing
# them sequentially (well there are limited modifiers so you
# might have to press a maximum of 2 keys simultaneously).
# An example of this can be seen in the template.o table.
# There are also templates (just add a template key like in
# user_view), they are defined under [template.<name>]

#injected into every map as key that shows the maps keybinds
#including Esc is useful as prefix for commands while text input mode is active
help_prefixes = ["?", "esc"]

[logger]
template = ["g"]
space="space"
up="messages-up"
down="messages-down"
left="left"
right="right"
"+"="plus"
"-"="minus"
h="hide"
f="focus"
C-up="target-up"
C-down="target-down"
esc = "escape"
q="quit"

[stats]
template = ["g"]
q="quit"

[fetch]
template = ["g"]
q = "quit"

[play_mpv]
template = ["g"]
q = "quit"
space = "pause"
enter = "pause"

[form]
template = ["g", "m"]
backspace = "delete"
tab = "down"
enter = "enter"
space = "enter"
q = "quit"

[user_view]
template = ["ud", "q", "e", "g"]
r = "reload"
left = "prev"
back-tab = "prev"
right = "next"
tab = "next"

[home_screen]
template = ["m", "e", "g"]
r = "reload"

[error]
template = ["m", "g", "q"]
k = "kill"

[item_details]
template = ["ud", "q", "e", "g"]
r = "reload"

[item_list_details]
template = ["m", "e", "g"]
r = "reload"
"C-r" = "refresh-parent-item"





[template.q]
q = "quit"

[template.ud]
up = "up"
down = "down"

[template.lr]
left = "left"
right = "right"

[template.m]
template = ["q", "ud", "lr"]

[template.e]
o = "open"
p = "play"
enter = "activate"
# sub maps have a name that is displayed in the keybind help / context view
# all other key value combinations are normal keybinds (and can even be another sub map or an template)
O = {name = "open-", e = "open-episode", S = "open-season", s = "open-series"}
R = "refresh-item"
w = "set-watched"
u = "unset-watched"

[template.g]
s = {name="show-", s="show-stats", l="show-logs"}
