[dependencies]
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-error-widget = {path = "../../widgets/error"}
jellyhaj-keybinds-widget = {path = "../../widgets/keybinds"}
jellyhaj-widgets-core = {path = "../../widgets/core"}
color-eyre.workspace = true
tracing.workspace = true
spawn = { path = "../../spawn" }

[package]
name = "jellyhaj-error-view"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
