[package]
name = "jellyhaj-metadata-editor-widget"

[package.version ]
workspace = true

[package.edition ]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
color-eyre.workspace = true
jellyfin = { path = "../../jellyfin-rs", features = ["valuable"] }
jellyhaj-core = { path = "../../jellyhaj-core" }
jellyhaj-form-widget = { path = "../form" }
jellyhaj-keybinds-widget = { path = "../keybinds" }
jellyhaj-widgets-core = { path = "../core" }
jiff.workspace = true
valuable.workspace = true

[lints]
workspace = true
