[dependencies]
color-eyre = {workspace = true}
futures-util = {workspace = true}
jellyfin = {path = "../jellyfin-rs"}
player-core = {path = "../player-core"}
spawn = {path = "../spawn"}
tokio = {features = ["rt"], workspace = true}
tracing = {workspace = true}

[package]
name = "player-jellyfin"

rust-version.workspace = true
version.workspace = true
edition.workspace = true

[lints]
workspace = true
