[dependencies]
config = {path = "../../config"}
futures-channel = {features = ["sink"], version = "0.3.31"}
futures-intrusive = "0.5.0"
futures-util = {features = ["sink"], workspace = true}
jellyhaj-async-task = {path = "../../async-task"}
spawn = {path = "../../spawn"}
color-eyre.workspace = true
parking_lot.workspace = true
pin-project-lite.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
tokio-util.workspace = true
tracing.workspace = true
valuable.workspace = true

[package]
name = "jellyhaj-widgets-core"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
