[dependencies]
jellyhaj-widgets-core = {path = "../core"}
stats-data = {path = "../../stats-data"}
tokio = {features = ["time"], workspace = true}
futures-util.workspace = true
ratatui.workspace = true
tracing.workspace = true
valuable.workspace = true

[package]
name = "jellyhaj-stats-widget"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
