[dependencies]
jellyfin = {path = "../../jellyfin-rs"}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-entry-widget = {path = "../entry"}
jellyhaj-item-list = {path = "../item-list"}
jellyhaj-widgets-core = {path = "../core"}
color-eyre.workspace = true
ratatui.workspace = true
textwrap.workspace = true
valuable.workspace = true
jellyhaj-image = { path = "../image" }
jellyhaj-tabs-widget = { path = "../tabs" }
sqlx.workspace = true
spawn = { path = "../../spawn" }
tokio = { workspace = true, features = ["sync"] }
jellyhaj-event-listener = { path = "../../event-listener" }

[package]
name = "jellyhaj-item-details-widget"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
