[dependencies]
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-keybinds-widget = {path = "../../widgets/keybinds"}
jellyhaj-stats-widget = {path = "../../widgets/stats"}
jellyhaj-widgets-core = {path = "../../widgets/core"}
color-eyre.workspace = true
spawn = { path = "../../spawn" }
stats-data = { path = "../../stats-data" }

[package]
name = "jellyhaj-stats-view"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true



[lints]
workspace = true
