[package]
name = "jellyhaj-tabs-widget"

[package.version ]
workspace = true

[package.edition ]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
color-eyre.workspace = true
jellyhaj-core = { path = "../../jellyhaj-core" }
jellyhaj-tabs-widget-macro = { path = "../tabs-macro" }
jellyhaj-widgets-core = { path = "../core" }
[lints]
workspace = true
