[dependencies]
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-widgets-core = {path = "../core"}
keybinds = {path = "../../keybinds"}
color-eyre.workspace = true
itertools.workspace = true
ratatui.workspace = true
tracing.workspace = true

[package]
name = "jellyhaj-keybinds-widget"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
