[dependencies]
jellyfin = {path = "../../jellyfin-rs"}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-fetch-view = {path = "../fetch"}
jellyhaj-home-screen-widget = {path = "../../widgets/home-screen"}
tokio = {features = ["macros"], workspace = true}
color-eyre.workspace = true
futures-util.workspace = true
jellyhaj-context = {  path = "../../context" }

[package]
name = "jellyhaj-home-screen-view"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
