[dependencies]
color-eyre = {workspace = true}
crossterm = {workspace = true}
keybinds-derive = {path = "../keybinds-derive"}
serde = {workspace = true}
futures-core.workspace = true
valuable.workspace = true

[package]
name = "keybinds"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
