[dependencies]
jellyfin = {path = "../../jellyfin-rs"}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-fetch-view = {path = "../fetch"}
jellyhaj-form-widget = {path = "../../widgets/form"}
jellyhaj-keybinds-widget = {path = "../../widgets/keybinds"}
jellyhaj-refresh-item-widget = {path = "../../widgets/refresh-item"}
jellyhaj-widgets-core = {path = "../../widgets/core"}
color-eyre.workspace = true
jellyhaj-context = { path = "../../context" }

[package]
name = "jellyhaj-refresh-item-view"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
