[dependencies]
jellyhaj-widgets-core = {path = "../core"}
ansi-to-tui.workspace = true
color-eyre.workspace = true
ratatui.workspace = true
valuable.workspace = true

[package]
name = "jellyhaj-error-widget"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
