[dependencies]
color-eyre = {workspace = true}
jellyfin = {path = "../jellyfin-rs"}
player-core = {path = "../player-core"}
zbus = {workspace = true}
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
jellyhaj-core = { path = "../jellyhaj-core" }

[package]
name = "player-mpris"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
