[dependencies]
jellyfin = {path = "../../jellyfin-rs"}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-entry-widget = {path = "../../widgets/entry"}
jellyhaj-fetch-view = {path = "../fetch"}
jellyhaj-item-details-widget = {path = "../../widgets/item-details"}
jellyhaj-item-list = {path = "../../widgets/item-list"}
jellyhaj-keybinds-widget = {path = "../../widgets/keybinds"}
jellyhaj-widgets-core = {path = "../../widgets/core"}
tokio = {features = ["macros"], workspace = true}
color-eyre.workspace = true
tracing.workspace = true
jellyhaj-tabs-widget = { path = "../../widgets/tabs" }
jellyhaj-context = { path = "../../context" }

[package]
name = "jellyhaj-item-details-view"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
