[dependencies]
jellyfin = {path = "../../jellyfin-rs"}
jellyhaj-core = {path = "../../jellyhaj-core"}
jellyhaj-entry-widget = {path = "../entry"}
jellyhaj-event-listener = { path = "../../event-listener" }
jellyhaj-item-screen = {path = "../item-screen"}
jellyhaj-keybinds-widget = {path = "../keybinds"}
jellyhaj-widgets-core = {path = "../core"}
spawn = { path = "../../spawn" }
sqlx.workspace = true
tokio = { workspace = true, features = ["sync"] }
valuable.workspace = true

[package]
name = "jellyhaj-home-screen-widget"

[package.edition ]
workspace = true

[package.version ]
workspace = true

[package.rust-version]
workspace = true


[lints]
workspace = true
