name: "Nix Build"
on:
  push:
    branches: [ "main" ]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15
    - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c
      with:
        name:
            owo-uwu-nyaa
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#jellyhaj
    - run: nix flake check
    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      if: ${{ failure() }}
      with:
        name: nix-logs
        path: /nix/var/log/nix/drvs
        compression-level: 0
