name: "cargo test"
on:
  pull_request:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, ubuntu-26.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - name: Install dependencies (Ubuntu)
      if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      run: |
        sudo apt-get update
        sudo apt-get install libmpv-dev libchafa-dev
    - name: Install dependencies (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew update
        brew install mpv chafa
    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4
      with:
        add-rust-environment-hash-key: false
        cache-on-failure: true
        cache-all-crates: true
        cache-workspace-crates: true
        key: ${{ matrix.os }}
    - run: cargo +stable test --workspace -- --test-threads 1
